# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup Secret Box developer environment
    init: |
      echo "Install Vue"
      yarn global add @vue/cli
      echo "Setup Rust toolchain"
      rustup install nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup default nightly
      echo "Pull LocalSecret image"
      docker pull ghcr.io/scrtlabs/localsecret
      echo "Pull contract optimizer image"
      docker pull enigmampc/secret-contract-optimizer
      gp sync-done secretbox-env
    command: |
      exit

  - name: Launch LocalSecret
    before: |
      echo "Wait for Secret Box developer environment"
      gp sync-await secretbox-env
    command: |
      echo "Starting localsecret blockchain"
      make localsecret &
      gp ports await 9090
      gp sync-done blockchain
      docker container logs -f localsecret
    openMode: split-right

  - name: Secret Box Contract
    before: |
      echo "Wait for LocalSecret instance"
      gp sync-await blockchain
      echo "Compile secret box contract"
      make build
      echo "Build schema files"
      make schema
      echo "Run unit tests"
      make unit-test
    command: |
      echo "Deploy and instantiate secret contract to local blockchain"
      gp env SECRET_BOX_ADDRESS=`scripts/create_secret_box.sh`
      gp sync-done secretbox-contract
    openMode: split-right

  - name: Secret Box Frontend
    init: |
      cd app
      echo "Install project dependencies"
      yarn install 
    command: |
      gp sync-await secretbox-contract
      cd app
      yarn dev
      gp open tutorial/guide.md
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5173
    onOpen: open-preview
